# https://github.com/sclorg/nginx-container/blob/master/1.20/README.md

FROM registry.access.redhat.com/ubi8/nginx-120

RUN mkdir ./app1 && \
    chmod 775 ./app1

ADD index.html ./app1/index.html

CMD nginx -g "daemon off;"
