{{ range .Values.applications }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}"
spec:
  ports:
    - targetPort: 8080
      port: 8080
      protocol: TCP
  selector:
    app: "{{ $.Release.Name }}-{{ .name }}"
{{ end }}
